Gasolineras/Controllers/GasolinerasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gasolineras.Models;
using Newtonsoft.Json;

namespace Gasolineras.Controllers
{
    public class GasolinerasController : Controller
    {
        private GasolinerasEntities1 db = new GasolinerasEntities1();

        // GET: Gasolineras

        public ActionResult Index()
        {

           
            return View();
        }

        // GET: Gasolineras
        public ActionResult Index2()
        {
            var gasolineras = db.Gasolineras.Include(g => g.Marca1);
            return View(gasolineras.ToList());
        }


        public JsonResult GetMapMarker()
        {
            db.Configuration.ProxyCreationEnabled = false;
            var ListaGasolineras = db.Gasolineras.ToList();

            return Json(ListaGasolineras, JsonRequestBehavior.AllowGet);
        }

        // GET: Gasolineras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gasolinera gasolinera = db.Gasolineras.Find(id);
            if (gasolinera == null)
            {
                return HttpNotFound();
            }
            return View(gasolinera);
        }

        // GET: Gasolineras/Create
        public ActionResult Create()
        {
            ViewBag.Amenidades = new SelectList(db.Amenidades, "Id", "Descripcion");
            ViewBag.Marca = new SelectList(db.Marcas, "Id", "Descripcion");
            return View();
        }

        // POST: Gasolineras/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Latitud,Longitud,Nombre,Marca,Amenidades,PrecioMagna,PrecioPremium,PrecioDiesel,HoraApertura,HoraCierre")] Gasolinera gasolinera, int[] Amenidades)
        {
            if (ModelState.IsValid)
            {
                string amenidades = Amenidades != null ? String.Join(",", Amenidades.Select(p => p.ToString()).ToArray()) : null;
                gasolinera.Amenidades = amenidades;
                db.Gasolineras.Add(gasolinera);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Marca = new SelectList(db.Marcas, "Id", "Descripcion", gasolinera.Marca);
            return View(gasolinera);
        }

        // GET: Gasolineras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gasolinera gasolinera = db.Gasolineras.Find(id);
            if (gasolinera == null)
            {
                return HttpNotFound();
            }
            ViewBag.Marca = new SelectList(db.Marcas, "Id", "Descripcion", gasolinera.Marca);
            return View(gasolinera);
        }

        // POST: Gasolineras/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Latitud,Longitud,Nombre,Marca,Amenidades,PrecioMagna,PrecioPremium,PrecioDiesel,HoraApertura,HoraCierre")] Gasolinera gasolinera)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gasolinera).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Marca = new SelectList(db.Marcas, "Id", "Descripcion", gasolinera.Marca);
            return View(gasolinera);
        }

        // GET: Gasolineras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gasolinera gasolinera = db.Gasolineras.Find(id);
            if (gasolinera == null)
            {
                return HttpNotFound();
            }
            return View(gasolinera);
        }

        // POST: Gasolineras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Gasolinera gasolinera = db.Gasolineras.Find(id);
            db.Gasolineras.Remove(gasolinera);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gasolineras/Controllers/SuscripcionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gasolineras.Controllers
{
    public class SuscripcionController : Controller
    {
        // GET: Suscripcion
        public ActionResult Index()
        {
            return View();
        }

        // GET: Suscripcion/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Suscripcion/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Suscripcion/Cuenta
        public ActionResult Cuenta()
        {
            return View();
        }


        // POST: Suscripcion/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Suscripcion/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Suscripcion/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Suscripcion/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Suscripcion/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Gasolineras/Views/Suscripcion/Cuenta.cshtml
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">



<Gasolineras.Models.Gasolinera>

    <center>
        <h2>@ViewBag.Title</h2>
    </center>

    @using (Html.BeginForm("Index", "Gasolineras", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <center>
            <h4>Datos de la tarjeta</h4>
        </center>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })

        <center>
            <label for="exampleFormControlInput1" class="form-label">Número de tarjeta</label>
            <input class="form-control form-control-sm" type="text" placeholder="Número de tarjeta" aria-label=".form-control-sm example" >
            <br />
        </center>

        <center>
            <label for="exampleFormControlInput1" class="form-label">Nombre y apellido</label>
            <input class="form-control form-control-sm" type="text" placeholder="Nombre y apellido" aria-label=".form-control-sm example" >
            <br />
        </center>

        <center>
            <label for="exampleFormControlInput1" class="form-label">Vencimiento</label>
            <input class="form-control form-control-sm" type="text" placeholder="Vencimiento" aria-label=".form-control-sm example" >
            <br />
        </center>

        <center>
            <label for="exampleFormControlInput1" class="form-label">Código de seguridad</label>
            <input class="form-control form-control-sm" type="text" placeholder="Código de seguridad" aria-label=".form-control-sm example" >
            <br />
        </center>

        <center>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">
                Pagar
            </button>
        </center>
        <!-- Modal -->
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">Pago confirmado</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" href="@Url.Action("Index","Gasolineras")">Cerrar</button>

                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <center>
                    <br>
                    <br>
                    <input type="submit" class="btn btn-admin" value="Volver al mapa" />
                </center>
            </div>
        </div>




    }

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

Gasolineras/Views/Suscripcion/Index.cshtml
<Gasolineras.Models.Gasolinera>

    <center>
        <h2>@ViewBag.Title</h2>
    </center>

    @using (Html.BeginForm("Cuenta", "Suscripcion", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        <center>
            <h4>Suscríbase a la aplicación</h4>
        </center>
        <hr />
        @Html.ValidationSummary("", new { @class = "text-danger" })

        <center>
            <label for="exampleFormControlInput1" class="form-label">Nombre de usuario</label>
            <input class="form-control form-control-sm" type="text" placeholder="Usuario" aria-label=".form-control-sm example" required>
            <br />
        </center>

        <center>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="form-label">Dirección de correo electrónico</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" required>
            </div>

        </center>

        <center>
            <div class="form-group">
                <label for="exampleFormControlInput1" class="form-label">Contraseña</label>
                <input type="password" class="form-control" id="exampleFormControlInput1" placeholder="Contraseña" required>
            </div>

        </center>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <center>
                    <br>
                    <input type="submit" class="btn btn-admin" value="Suscribirse" />
                </center>
            </div>
        </div>
    }